_target_: pytorchlightning_trainer.module.ProtoNetWithLITE

pretrained_backbone_checkpoint_path: "/home/sebastian.cavada/Documents/scsv/semester2/CV703/ORBIT-2022-winner-method/pretrained/phinet/state_dict.pth_v2.tar"
backbone_network: "phinet"
unfreeze_backbone: True
freeze_BN_layer: True
normalization_layer: "basic"
use_adapt_features: False
feature_adaptation_method: "generate"
classifier: "feat"
video_clip_length: 8
episode_subset_mini_batch_size: 8
num_episodes_per_meta_batch: 16
num_lite_samples: 8
use_two_gpus: False

lr: 0.0001



